# Setup
title:        Perfect Blog
tagline:      The best personal blog!
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Perfect Blog Group
  url:        http://perfectblog.gitHub.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
